### ISSUE TITLE
Question: How to trigger CamQuery to start tainting

### ISSUE THREAD

**Issue by musi00** [CamFlow/camflow-query#5]
Hello,

We are trying to use Camflow and CamQuery for the following scenario.

Host A holds sensitive data as files.  When Host B requests data from Host A we want CamQuery which is running on Host B to be triggered to start tainting the data received from A.  The idea is that any further modifications of this sensitive file by any application on Host B, the taint will be propogated and blocked if there is an attempt to send this file to a socket on Host B.

Questions related to Scenario:
1) Is is possible to trigger CamQuery from userspace to start tainting at a specific point in time (when response is received from Host A)?
2) How would you tell CamQuery to taint the specific file received from A.  Would we use the specific socket open between A and B to let CamQuery know that any data coming through that socket needs to be tainted?
3) It seems the configuration of camflow already allows for propogation, however CamQuery is also able to propogate labels by implemening the out_edge, in_edge functions.  Which of those methods is best for this scenario? are they compatible?

**Comment by tfjmp** [comment]
1. From userspace not certain (though in theory, you can add taint programmatically or through CLI so maybe), otherwise from within a kernel query it is trivial.
2. I am not fully certain of the scenario you are describing. However, yes if you taint socket A any nodes derived from this socket should be tainted (including nodes representing a file written by a process that read from the socket).
3. I am not sure I fully understand the question, but this is the code that uses the CamQuery framework to handle propagate and tainting: https://github.com/CamFlow/camflow-dev/blob/master/security/provenance/propagate.c#L18 You will need to write some code to block the data from being sent over the socket, but that can be with a relatively simple if statement and returning `PROVENANCE_PREVENT_FLOW ` when appropriate (https://github.com/CamFlow/camflow-dev/blob/master/include/linux/provenance_query.h#L22).

**Comment by tfjmp** [comment]
Closing the issue. Please, do reopen if you have further questions.
